# See https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
github:
  description: "A component-oriented framework for creating highly scalable web applications in Java."
  homepage: "https://tapestry.apache.org"
  labels:
    - java
    - apache

  features:
    wiki: false
    issues: false
    projects: false

  autolink_jira:
    - TAP5

  protected_branches:
    # no force push to master
    master: {}
